# Basics (from video by  @sentdex )

In [1]:
import torch

In [5]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [7]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
x.shape

torch.Size([2, 5])

In [10]:
y = torch.rand([2,5])

print(y)

tensor([[0.0085, 0.3641, 0.8996, 0.5590, 0.2122],
        [0.4968, 0.8856, 0.1954, 0.5083, 0.9783]])


In [13]:
y = y.view([1,10])

y

tensor([[0.0085, 0.3641, 0.8996, 0.5590, 0.2122, 0.4968, 0.8856, 0.1954, 0.5083,
         0.9783]])